import React, { useEffect, useState } from 'react';
import type { FormData, ValidationResult } from '../types';
import { REACTION_TYPES } from '../constants';
import { validateFormData } from '../services/validation';

interface Props { formData: FormData; setFormData: React.Dispatch<React.SetStateAction<FormData>>; onSubmit: (event: React.FormEvent) => void; isLoading: boolean; onValidation: (result: ValidationResult) => void; }

const Field: React.FC<{ label: string; value: string; onChange: (value: string) => void; unit?: string; help?: string; error?: string; type?: string }> = ({ label, value, onChange, unit, help, error, type = 'text' }) => <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-200">{label}{unit ? <span className="ml-1 text-xs font-normal text-slate-400">({unit})</span> : null}</span><div className="relative"><input type={type} value={value} onChange={(event) => onChange(event.target.value)} className={`w-full rounded-lg border bg-slate-950/60 px-3 py-2.5 text-slate-100 outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/30 ${error ? 'border-rose-500' : 'border-slate-700'}`} aria-invalid={Boolean(error)} />{help && <span className="pointer-events-none absolute right-2 top-3 text-xs text-slate-500">{help}</span>}</div>{error ? <span className="mt-1 block text-xs text-rose-300">{error}</span> : null}</label>;

export default function KineticsForm({ formData, setFormData, onSubmit, isLoading, onValidation }: Props) {
  const [validation, setValidation] = useState<ValidationResult>({ valid: false, errors: [], warnings: [] });
  useEffect(() => { const result = validateFormData(formData); setValidation(result); onValidation(result); }, [formData, onValidation]);
  const update = (key: keyof FormData, value: string) => setFormData((current) => ({ ...current, [key]: value }));
  const updateMonomer = (id: string, key: 'name' | 'concentration', value: string) => setFormData((current) => ({ ...current, monomers: current.monomers.map((item) => item.id === id ? { ...item, [key]: value } : item) }));
  const addMonomer = () => setFormData((current) => current.monomers.length >= 2 ? current : ({ ...current, monomers: [...current.monomers, { id: `monomer_${Date.now()}`, name: '', concentration: '' }] }));
  const removeMonomer = (id: string) => setFormData((current) => current.monomers.length <= 1 ? current : ({ ...current, monomers: current.monomers.filter((item) => item.id !== id) }));
  const setRatio = (key: 'r1' | 'r2', value: string) => setFormData((current) => ({ ...current, reactivityRatios: { ...current.reactivityRatios, [key]: value } }));
  return <form onSubmit={onSubmit} className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-5 shadow-xl">
    <div><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-white">Experiment setup</h2><span className="rounded-full bg-cyan-400/10 px-2 py-1 text-xs text-cyan-300">Step 1 of 2</span></div><p className="mt-1 text-sm text-slate-400">Enter measured or planned conditions. Values are checked for ranges, but chemical identity is not automatically verified.</p></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-bold uppercase tracking-wide text-cyan-300">Monomers</h3><button type="button" onClick={addMonomer} disabled={formData.monomers.length >= 2} className="text-xs font-semibold text-cyan-300 disabled:text-slate-600">+ Add second</button></div>{formData.monomers.map((monomer) => <div key={monomer.id} className="grid grid-cols-[1fr_110px_26px] gap-2"><Field label="Name" value={monomer.name} onChange={(value) => updateMonomer(monomer.id, 'name', value)} /><Field label="Initial concentration" unit="mol/L" value={monomer.concentration} onChange={(value) => updateMonomer(monomer.id, 'concentration', value)} type="number" /><button type="button" onClick={() => removeMonomer(monomer.id)} disabled={formData.monomers.length <= 1} className="mt-7 text-slate-500 hover:text-rose-300 disabled:opacity-30" aria-label="Remove monomer">×</button></div>)}</div>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Initiator or catalyst" value={formData.initiator} onChange={(value) => update('initiator', value)} /><Field label="Initiator concentration" unit="mol/L" value={formData.initiatorConcentration} onChange={(value) => update('initiatorConcentration', value)} type="number" /><Field label="Temperature" unit="°C" value={formData.temperature} onChange={(value) => update('temperature', value)} type="number" /><label className="block"><span className="mb-1 block text-sm font-semibold text-slate-200">Reaction type</span><select value={formData.reactionType} onChange={(event) => update('reactionType', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950/60 px-3 py-2.5 text-slate-100">{REACTION_TYPES.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></div>
    {formData.monomers.length === 2 && <div className="grid gap-4 rounded-xl border border-slate-800 bg-slate-950/30 p-3 sm:grid-cols-2"><Field label={`Reactivity ratio r1 (${formData.monomers[0].name || 'M1'})`} value={formData.reactivityRatios.r1} onChange={(value) => setRatio('r1', value)} type="number" /><Field label={`Reactivity ratio r2 (${formData.monomers[1].name || 'M2'})`} value={formData.reactivityRatios.r2} onChange={(value) => setRatio('r2', value)} type="number" /></div>}
    <details className="rounded-xl border border-slate-800 bg-slate-950/20 p-3"><summary className="cursor-pointer text-sm font-semibold text-slate-300">Optional chain-transfer and solvent inputs</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Chain-transfer agent" value={formData.chainTransferAgent} onChange={(value) => update('chainTransferAgent', value)} /><Field label="CTA concentration" unit="mol/L" value={formData.ctaConcentration} onChange={(value) => update('ctaConcentration', value)} type="number" /><Field label="Solvent" value={formData.solvent} onChange={(value) => update('solvent', value)} /><Field label="Solvent volume" unit="mL" value={formData.solventVolume} onChange={(value) => update('solventVolume', value)} type="number" /></div></details>
    {validation.warnings.length > 0 && <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-100"><strong className="block text-amber-300">Before you interpret results</strong><ul className="mt-1 list-disc space-y-1 pl-4">{validation.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}
    {validation.errors.length > 0 && <div className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-3 text-xs text-rose-200"><strong className="block text-rose-300">Input corrections required</strong><ul className="mt-1 list-disc space-y-1 pl-4">{validation.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}
    <button type="submit" disabled={isLoading || !validation.valid} className="w-full rounded-xl bg-cyan-500 px-4 py-3 font-bold text-slate-950 transition hover:bg-cyan-300 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-500">{isLoading ? 'Running screening model…' : 'Run transparent screening model'}</button>
  </form>;
}
