import React from 'react';
import type { GeneratedData } from '../types';
import KineticsChart from './KineticsChart';
import DataTable from './DataTable';

function downloadCsv(data: GeneratedData) {
  const rows = [['time_min', ...data.kineticData[0] ? Object.keys(data.kineticData[0].conversion).map((key) => `${key}_percent`) : [], 'Mn_g_mol', 'Mw_g_mol', 'dispersity']];
  data.kineticData.forEach((point) => rows.push([String(point.time), ...Object.values(point.conversion).map((value) => value.toFixed(6)), point.molecularWeightMn.toFixed(6), point.molecularWeightMw.toFixed(6), point.dispersity.toFixed(6)]));
  const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'polymer-kinetics-screening.csv'; link.click(); URL.revokeObjectURL(url);
}

export default function ResultsDisplay({ data, isLoading, error }: { data: GeneratedData | null; isLoading: boolean; error: string | null }) {
  if (isLoading) return <div className="flex min-h-[620px] items-center justify-center rounded-2xl border border-slate-800 bg-slate-900/70"><div className="text-center"><div className="mx-auto mb-4 h-10 w-10 animate-spin rounded-full border-4 border-slate-700 border-t-cyan-400" /><h3 className="text-xl font-bold text-white">Running transparent model</h3><p className="mt-2 text-sm text-slate-400">Fetching optional chemical and literature metadata with safe timeouts.</p></div></div>;
  if (error) return <div className="flex min-h-[620px] items-center justify-center rounded-2xl border border-rose-500/30 bg-rose-500/5 p-8 text-center"><div><h3 className="text-xl font-bold text-rose-300">Could not run the workflow</h3><p className="mt-2 text-sm text-rose-200">{error}</p></div></div>;
  if (!data) return <div className="flex min-h-[620px] items-center justify-center rounded-2xl border border-dashed border-slate-700 bg-slate-900/50 p-8 text-center"><div><div className="mx-auto mb-4 text-5xl">∿</div><h3 className="text-xl font-bold text-slate-200">Your evidence-aware workspace</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-400">Run the demo or enter conditions to generate a transparent screening curve, inspect assumptions, and optionally enrich names from public sources.</p></div></div>;
  return <div className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-5 shadow-xl"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 inline-flex rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1 text-xs font-bold text-amber-200">EXPLORATORY SCREENING ESTIMATE</div><h2 className="text-2xl font-bold text-white">Kinetic profile</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-slate-400">{data.summary}</p></div><button type="button" onClick={() => downloadCsv(data)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm font-semibold text-slate-200 hover:border-cyan-400 hover:text-cyan-300">Export CSV</button></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-950/60 p-3"><span className="text-xs text-slate-500">Model</span><strong className="mt-1 block text-sm text-white">{data.diagnostics.modelName}</strong></div><div className="rounded-xl bg-slate-950/60 p-3"><span className="text-xs text-slate-500">Final conversion</span><strong className="mt-1 block text-sm text-cyan-300">{data.kineticData.at(-1)?.conversion.overall.toFixed(1)}%</strong></div><div className="rounded-xl bg-slate-950/60 p-3"><span className="text-xs text-slate-500">Record / input</span><strong className="mt-1 block text-xs text-white">v{data.recordVersion} · {data.inputHash}</strong></div><div className="rounded-xl bg-slate-950/60 p-3"><span className="text-xs text-slate-500">Created</span><strong className="mt-1 block text-sm text-white">{new Date(data.createdAt).toLocaleTimeString()}</strong></div></div>
    <div className="h-[430px] rounded-xl border border-slate-800 bg-slate-950/40 p-2"><KineticsChart data={data.kineticData} /></div><DataTable data={data.kineticData} />
    <details className="rounded-xl border border-slate-800 p-4"><summary className="cursor-pointer font-semibold text-slate-200">Inspect assumptions and warnings</summary><div className="mt-3 space-y-3 text-sm text-slate-400"><ul className="list-disc space-y-1 pl-5">{data.diagnostics.assumptions.map((item) => <li key={item}>{item}</li>)}</ul><ul className="list-disc space-y-1 pl-5 text-amber-200">{data.diagnostics.warnings.map((item) => <li key={item}>{item}</li>)}</ul></div></details>
    {data.chemicalRecords.length > 0 && <section><h3 className="mb-2 font-bold text-white">Chemical metadata</h3><div className="grid gap-3 sm:grid-cols-2">{data.chemicalRecords.map((record) => <div key={record.query} className="rounded-xl border border-slate-800 p-3 text-sm"><strong className="text-cyan-300">{record.query}</strong>{record.warning ? <p className="mt-1 text-amber-200">{record.warning}</p> : <p className="mt-1 text-slate-400">{record.molecularFormula || 'Formula unavailable'} · {record.molecularWeight ? `${record.molecularWeight.toFixed(3)} g/mol` : 'MW unavailable'}</p>}<a className="mt-2 inline-block text-xs text-cyan-400 hover:underline" href={record.source.uri} target="_blank" rel="noreferrer">View source</a></div>)}</div></section>}
    {data.sources.length > 0 && <section><h3 className="mb-2 font-bold text-white">Provenance</h3><ul className="space-y-1 text-xs text-slate-400">{data.sources.map((source) => <li key={source.uri + source.title}><a href={source.uri} target="_blank" rel="noreferrer" className="text-cyan-400 hover:underline">{source.title}</a> · {source.status} · retrieved {new Date(source.retrievedAt).toLocaleString()}</li>)}</ul></section>}
  </div>;
}
